### ISSUE TITLE
Solcast 3.1.4 Update Breaking Dashboard

### ISSUE THREAD

**Issue by cschutte** [slipx06/Sunsynk-Home-Assistant-Dash#2]
Hi Slipx

Is your dashboard sill working after the latest 3.1.4 Solcast update? It seem the Data Generator is not working at the moment with the current dashboard?

Sorry to bother with this...

**Comment by slipx06** [comment]
Hi. I've just pushed a fix. Thanks

**Comment by cschutte** [comment]
I confirm - works perfectly again - thanks!
