### ISSUE TITLE
Unable to write or read settings from inverter after firmware update.

### ISSUE THREAD

**Issue by ameran** [slipx06/Sunsynk-Home-Assistant-Dash#20]
I've had my system running for months now and it's been fine.

We had Deye upgrade the firmware of the unit because it wasn't recognising the new battery. After that the ESP would connect and read, but all the data had NaN values.

Dug around on the inverter itself and the Modbus was changed from 01 to 00, must have happened when the new firmware was installed. Changed that in the code and it started reading again.

Now the problem is this:

![image](https://github.com/user-attachments/assets/95e304db-c8e4-43b9-b673-6a07a0f4ad33)

It's not reading the time zone values, only displaying 21474 and also not displaying the SOC% only NaN.

What do I do to fix this?

Example of the Write settings:

![image](https://github.com/user-attachments/assets/8a1ec3e6-2133-4c42-9b1b-50bc4c2090c1)

![image](https://github.com/user-attachments/assets/e44002b7-6ee4-4dab-9678-b2b33a8426c1)
![image](https://github.com/user-attachments/assets/6531bcd6-cf13-48d9-b818-a2cf81104101)
![image](https://github.com/user-attachments/assets/69504fe5-b228-4775-9527-c2b5ba82f95d)

**Comment by slipx06** [comment]
Hi. Have you looked at your ESPHome logs?

**Comment by ameran** [comment]
Yip, no errors, only this:
![image](https://github.com/user-attachments/assets/59c94d7c-c4b8-4922-b4be-39c3da3edf17)
![image](https://github.com/user-attachments/assets/9e4a745d-543f-4780-9a47-f1eb8bfd253f)

It was all working 100% before we did the firmware upgrade, since then it seems like registers have changed.
I'd love to know where to start looking.

**Comment by slipx06** [comment]
Looks like it's not reading any of the System Timer info?
You can try read the raw register values and see what comes back.

Registers 
250-255 - Times
274-279 - Charge
268-273 - SOC
256-251 - Power

Have you also checked to make sure there are no other errors for the other registers?

**Comment by ameran** [comment]
i'm clueless.

The other registers are definitely pulling values:
![image](https://github.com/user-attachments/assets/6ffe6cec-fbc1-4d8c-85b5-b13769edc124)
It's just the ones to do with the timer info.

I've reverted to your code and only changed the details relevant to get it connected to my network and the inverter, incase I have a typo somewhere, but its the same.
The same registers come back with the strange values or unknown.

Do you think the inverter address could be an issue?
before it was 0x01, its now 0x00.

**Comment by ameran** [comment]
I fixed it, it wasn't anything in the code!
It was the inverter, when it was reset the modbus SN setting was set back to 00, I changed it to 01 and its reading all the settings again.
