### ISSUE TITLE
Using Solcast insead of Meteo Solar Forecast

### ISSUE THREAD

**Issue by Ben00793** [slipx06/Sunsynk-Home-Assistant-Dash#22]
Hello,
I was just wondering if it would be possible to use Solcast sensors insead of Meteo Solar Forecast in this card:
![image](https://github.com/user-attachments/assets/8ca3f62b-ed8c-4858-be4f-74e715c99c14)

if yes could you please help me with what do I need to change in the code?
I assume this is the part that needs changing, but I have no idea how:

filters:
      - fn: |
          ({meta}) => ({
             xs: meta.wh_period.map(({ start }) => new Date(start)),
             ys: meta.wh_period.map(({ value }) => value),
          })

Thank you!

**Comment by Ben00793** [comment]
So far this is how far I got:
type: custom:plotly-graph
entities:
  - entity: sensor.solcast_pv_forecast_forecast_today
    name: PV Forecast
    line:
      color: rgb(125, 125, 125)
      shape: spline
    fill: tozeroy
    filters:
      - fn: |
          ({meta}) => {
            const forecast = meta.DetailedForecast;
            const xs = forecast.map(item => new Date(item.period_start));
            const ys = forecast.map(item => item.pv_estimate);
            return { xs, ys };
          }
    yaxis: y1
    showlegend: true

It gives me this error: Error: at [entities.0.filters.0]: Error in filter: TypeError: Cannot read properties of undefined (reading 'map')
Attributes of sensor.solcast_pv_forecast_forecast_today:
Attributes
Dayname
Wednesday
DataCorrect
true
DetailedForecast
- period_start: '2024-09-04T00:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T00:30:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T01:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T01:30:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T02:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T02:30:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T03:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T03:30:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T04:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T04:30:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T05:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T05:30:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T06:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T06:30:00+01:00'
pv_estimate: 0.0386
pv_estimate10: 0.0386
pv_estimate90: 0.0459
- period_start: '2024-09-04T07:00:00+01:00'
pv_estimate: 0.0752
pv_estimate10: 0.0518
pv_estimate90: 0.0883
- period_start: '2024-09-04T07:30:00+01:00'
pv_estimate: 0.1136
pv_estimate10: 0.0698
pv_estimate90: 0.2089
- period_start: '2024-09-04T08:00:00+01:00'
pv_estimate: 0.5539
pv_estimate10: 0.2372
pv_estimate90: 0.7653
- period_start: '2024-09-04T08:30:00+01:00'
pv_estimate: 0.6364
pv_estimate10: 0.212
pv_estimate90: 0.9666
- period_start: '2024-09-04T09:00:00+01:00'
pv_estimate: 0.6453
pv_estimate10: 0.4208
pv_estimate90: 0.992
- period_start: '2024-09-04T09:30:00+01:00'
pv_estimate: 0.7775
pv_estimate10: 0.3022
pv_estimate90: 1.2652
- period_start: '2024-09-04T10:00:00+01:00'
pv_estimate: 0.9619
pv_estimate10: 0.4239
pv_estimate90: 1.2847
- period_start: '2024-09-04T10:30:00+01:00'
pv_estimate: 1.0668
pv_estimate10: 0.4354
pv_estimate90: 1.3814
- period_start: '2024-09-04T11:00:00+01:00'
pv_estimate: 1.1222
pv_estimate10: 0.3438
pv_estimate90: 1.4628
- period_start: '2024-09-04T11:30:00+01:00'
pv_estimate: 1.1625
pv_estimate10: 0.2986
pv_estimate90: 1.5242
- period_start: '2024-09-04T12:00:00+01:00'
pv_estimate: 1.1914
pv_estimate10: 0.2762
pv_estimate90: 1.5548
- period_start: '2024-09-04T12:30:00+01:00'
pv_estimate: 1.1892
pv_estimate10: 0.2546
pv_estimate90: 1.5413
- period_start: '2024-09-04T13:00:00+01:00'
pv_estimate: 1.2039
pv_estimate10: 0.269
pv_estimate90: 1.556
- period_start: '2024-09-04T13:30:00+01:00'
pv_estimate: 1.2213
pv_estimate10: 0.3026
pv_estimate90: 1.5424
- period_start: '2024-09-04T14:00:00+01:00'
pv_estimate: 1.2058
pv_estimate10: 0.311
pv_estimate90: 1.5082
- period_start: '2024-09-04T14:30:00+01:00'
pv_estimate: 1.1535
pv_estimate10: 0.297
pv_estimate90: 1.4443
- period_start: '2024-09-04T15:00:00+01:00'
pv_estimate: 1.0807
pv_estimate10: 0.2774
pv_estimate90: 1.3526
- period_start: '2024-09-04T15:30:00+01:00'
pv_estimate: 0.9762
pv_estimate10: 0.252
pv_estimate90: 1.2327
- period_start: '2024-09-04T16:00:00+01:00'
pv_estimate: 0.8164
pv_estimate10: 0.1838
pv_estimate90: 1.0921
- period_start: '2024-09-04T16:30:00+01:00'
pv_estimate: 0.6187
pv_estimate10: 0.0952
pv_estimate90: 0.9746
- period_start: '2024-09-04T17:00:00+01:00'
pv_estimate: 0.4646
pv_estimate10: 0.0632
pv_estimate90: 0.8828
- period_start: '2024-09-04T17:30:00+01:00'
pv_estimate: 0.3427
pv_estimate10: 0.048
pv_estimate90: 0.7814
- period_start: '2024-09-04T18:00:00+01:00'
pv_estimate: 0.2279
pv_estimate10: 0.0346
pv_estimate90: 0.6499
- period_start: '2024-09-04T18:30:00+01:00'
pv_estimate: 0.1116
pv_estimate10: 0.0212
pv_estimate90: 0.5074
- period_start: '2024-09-04T19:00:00+01:00'
pv_estimate: 0.043
pv_estimate10: 0.0092
pv_estimate90: 0.2806
- period_start: '2024-09-04T19:30:00+01:00'
pv_estimate: 0.0046
pv_estimate10: 0.0016
pv_estimate90: 0.0141
- period_start: '2024-09-04T20:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T20:30:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T21:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T21:30:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T22:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T22:30:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T23:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T23:30:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
DetailedHourly
- period_start: '2024-09-04T00:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T01:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T02:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T03:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T04:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T05:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T06:00:00+01:00'
pv_estimate: 0.0193
pv_estimate10: 0.0193
pv_estimate90: 0.023
- period_start: '2024-09-04T07:00:00+01:00'
pv_estimate: 0.0944
pv_estimate10: 0.0608
pv_estimate90: 0.1486
- period_start: '2024-09-04T08:00:00+01:00'
pv_estimate: 0.5951
pv_estimate10: 0.2246
pv_estimate90: 0.8659
- period_start: '2024-09-04T09:00:00+01:00'
pv_estimate: 0.7114
pv_estimate10: 0.3615
pv_estimate90: 1.1286
- period_start: '2024-09-04T10:00:00+01:00'
pv_estimate: 1.0143
pv_estimate10: 0.4296
pv_estimate90: 1.3331
- period_start: '2024-09-04T11:00:00+01:00'
pv_estimate: 1.1423
pv_estimate10: 0.3212
pv_estimate90: 1.4935
- period_start: '2024-09-04T12:00:00+01:00'
pv_estimate: 1.1903
pv_estimate10: 0.2654
pv_estimate90: 1.548
- period_start: '2024-09-04T13:00:00+01:00'
pv_estimate: 1.2126
pv_estimate10: 0.2858
pv_estimate90: 1.5492
- period_start: '2024-09-04T14:00:00+01:00'
pv_estimate: 1.1797
pv_estimate10: 0.304
pv_estimate90: 1.4762
- period_start: '2024-09-04T15:00:00+01:00'
pv_estimate: 1.0284
pv_estimate10: 0.2647
pv_estimate90: 1.2927
- period_start: '2024-09-04T16:00:00+01:00'
pv_estimate: 0.7176
pv_estimate10: 0.1395
pv_estimate90: 1.0333
- period_start: '2024-09-04T17:00:00+01:00'
pv_estimate: 0.4037
pv_estimate10: 0.0556
pv_estimate90: 0.8321
- period_start: '2024-09-04T18:00:00+01:00'
pv_estimate: 0.1698
pv_estimate10: 0.0279
pv_estimate90: 0.5786
- period_start: '2024-09-04T19:00:00+01:00'
pv_estimate: 0.0238
pv_estimate10: 0.0054
pv_estimate90: 0.1474
- period_start: '2024-09-04T20:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T21:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T22:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
- period_start: '2024-09-04T23:00:00+01:00'
pv_estimate: 0
pv_estimate10: 0
pv_estimate90: 0
50dc-6601-80eb-cb70
4.25
Estimate-50dc-6601-80eb-cb70
4.25
Estimate10-50dc-6601-80eb-cb70
1.5
Estimate90-50dc-6601-80eb-cb70
6.1
D8fb-a879-bc04-d20f
6.31
Estimate-d8fb-a879-bc04-d20f
6.31
Estimate10-d8fb-a879-bc04-d20f
1.57
Estimate90-d8fb-a879-bc04-d20f
8.84
Estimate
9.5
Estimate10
2.77
Estimate90
13.45

**Comment by slipx06** [comment]
Hi. Try this function

```

    filters:
      - fn: |
          ({meta}) => ({
             xs: meta.detailedForecast.map(({ period_start }) => new Date(period_start)),
             ys: meta.detailedForecast.map(({ pv_estimate }) => pv_estimate),
          })
```

**Comment by Ben00793** [comment]
It's working! Thanks very much!
