### ISSUE TITLE
Inverter Settings in Volts

### ISSUE THREAD

**Issue by Gavrik13** [slipx06/Sunsynk-Home-Assistant-Dash#6]
Hi!
How to read and write inverter settings when the settings are in volts, not percentages?
The battery is not connected to the inverter via CAN, but is controlled by voltage.

![image](https://github.com/slipx06/Sunsynk-Home-Assistant-Dash/assets/52272809/53eab559-951e-4422-b5be-1a21a08bb2d1)

**Comment by slipx06** [comment]
Hi. I will add it to the config.

**Comment by slipx06** [comment]
@Gavrik13 I've added those sensors. Can you please test

`number.sunsynk_prog1_voltage`
`number.sunsynk_prog2_voltage`
`number.sunsynk_prog3_voltage`
`number.sunsynk_prog4_voltage`
`number.sunsynk_prog5_voltage`
`number.sunsynk_prog6_voltage`

**Comment by Gavrik13** [comment]
Great ! 

![image](https://github.com/slipx06/Sunsynk-Home-Assistant-Dash/assets/52272809/ddfadfcf-b30c-4e56-8a64-5456e8a92a64)
