### ISSUE TITLE
Wrong  address

### ISSUE THREAD

**Issue by schpuntik** [slipx06/Sunsynk-Home-Assistant-Dash#7]
https://github.com/slipx06/Sunsynk-Home-Assistant-Dash/blob/c9bc183e5f664f6904018f47a488e54de0ec7e56/ESPHome-3P-12K-Sunsynk.yaml#L328

https://github.com/slipx06/Sunsynk-Home-Assistant-Dash/blob/c9bc183e5f664f6904018f47a488e54de0ec7e56/ESPHome-3P-12K-Sunsynk.yaml#L342

incorrect address should be 611 and 612

**Comment by slipx06** [comment]
Thanks. I have updated it.
