### ISSUE TITLE
F26BusUnbalance_Fault When I toggle Generator Charge

### ISSUE THREAD

**Issue by sakrlog** [slipx06/Sunsynk-Home-Assistant-Dash#9]
Hey, first thanks so much for the awesome work!

So I have modified the code a little bit because my nodeMCU kept on booting every ~40 mins. I figured that this could be because of the large code. And this turned out to be true. I'm using ai-thinker esp32 nodeMCU V1. This turned out to be true. So I have my updated code in _updated.txt_ file attached here.

So everything seems to be fine except when I toggle **Generator Charge** button. The inverter cut out the power to all ports and threw this error: **F26BusUnbalance_Fault**.

I was in off-grid mode with my backup generator turned on.
[updated.TXT](https://github.com/slipx06/Sunsynk-Home-Assistant-Dash/files/14345622/updated.TXT)

**Comment by slipx06** [comment]
Hi You can also disable the webserver and see it that helps. It might be a good idea to disable by default

# Enable webserver
#web_server:
#  port: 80

Sorry I cant help you with that error but perhaps check that all your fuses and circuit breakers are still good
